apiVersion: apps/v1
kind: Deployment
metadata:
  name: grefsgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grefsgr
  template:
    metadata:
      labels:
        app: grefsgr
    spec:
      containers:
      - image: okteto.dev/grefsgr:latest
        name: grefsgr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "39ab83b0-8528-4454-8ebe-677861511d80"
        - name: Vless_Path
          value: "/39ab83b0-8528-4454-8ebe-677861511d80-vless"
        - name: Vmess_UUID
          value: "39ab83b0-8528-4454-8ebe-677861511d80"
        - name: Vmess_Path
          value: "/39ab83b0-8528-4454-8ebe-677861511d80-vmess"
        - name: Share_Path
          value: "$Share_Path"
